[package]
name = "scripture-show"
version = "0.0.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.25.0"

[dependencies]
tauri = { version = "1.5", features = [ "macos-private-api", "api-all"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
quick-xml = "0.31.0"


[tauri.embed]
html = ["monitor.html", "choose_output.html"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
